// This file is auto-generated by: npx supabase gen types typescript --project-id <id> > src/types/database.ts
// Replace with the generated output after connecting your Supabase project.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      language_pairs: {
        Row: {
          id: string
          source_lang: string
          target_lang: string
          per_word_rate: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          source_lang: string
          target_lang: string
          per_word_rate: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          source_lang?: string
          target_lang?: string
          per_word_rate?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      specialty_multipliers: {
        Row: {
          id: string
          name: string
          multiplier: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          multiplier: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          multiplier?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      equipment_items: {
        Row: {
          id: string
          name: string
          description: string | null
          quantity_total: number
          quantity_available: number
          rate_per_day: number
          deposit_amount: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          quantity_total: number
          quantity_available: number
          rate_per_day: number
          deposit_amount?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          quantity_total?: number
          quantity_available?: number
          rate_per_day?: number
          deposit_amount?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      system_settings: {
        Row: {
          id: string
          key: string
          value: string
          description: string | null
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          key: string
          value: string
          description?: string | null
          updated_by?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          key?: string
          value?: string
          description?: string | null
          updated_by?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      clients: {
        Row: {
          id: string
          contact_name: string
          email: string
          phone: string | null
          company_name: string | null
          stripe_customer_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          contact_name: string
          email: string
          phone?: string | null
          company_name?: string | null
          stripe_customer_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          contact_name?: string
          email?: string
          phone?: string | null
          company_name?: string | null
          stripe_customer_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      employees: {
        Row: {
          id: string
          full_name: string
          role: 'admin' | 'employee'
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          full_name: string
          role?: 'admin' | 'employee'
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          role?: 'admin' | 'employee'
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      translators: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          language_pairs: string[]
          specialties: string[]
          stripe_connect_id: string | null
          stripe_connect_status: 'pending' | 'active' | 'restricted' | null
          is_active: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          phone?: string | null
          language_pairs?: string[]
          specialties?: string[]
          stripe_connect_id?: string | null
          stripe_connect_status?: 'pending' | 'active' | 'restricted' | null
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          language_pairs?: string[]
          specialties?: string[]
          stripe_connect_id?: string | null
          stripe_connect_status?: 'pending' | 'active' | 'restricted' | null
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      jobs: {
        Row: {
          id: string
          job_type: 'translation' | 'interpretation' | 'equipment_rental' | 'notary'
          status: string
          client_id: string
          source_lang: string | null
          target_lang: string | null
          specialty_id: string | null
          word_count: number | null
          document_path: string | null
          ai_draft_path: string | null
          translated_doc_path: string | null
          document_name: string | null
          ai_translation_started_at: string | null
          ai_translation_completed_at: string | null
          scheduled_at: string | null
          duration_minutes: number | null
          location_type: 'in_person' | 'phone' | 'video' | null
          location_details: string | null
          interpreter_notes: string | null
          rental_start_date: string | null
          rental_end_date: string | null
          rental_items: Json | null
          deposit_amount: number | null
          deposit_refunded_at: string | null
          dispatch_at: string | null
          return_at: string | null
          notary_service_type: 'notary' | 'apostille' | 'both' | null
          delivery_method: 'in_person' | 'mail' | null
          appointment_at: string | null
          quote_per_word_rate: number | null
          quote_multiplier: number | null
          quote_amount: number | null
          quote_adjusted_amount: number | null
          quote_finalized_at: string | null
          quote_token: string | null
          quote_token_expires_at: string | null
          quote_accepted_at: string | null
          stripe_payment_intent_id: string | null
          stripe_checkout_session_id: string | null
          invoice_number: string | null
          invoice_issued_at: string | null
          payment_collected_at: string | null
          assigned_translator_id: string | null
          assigned_at: string | null
          deadline_at: string | null
          delivered_at: string | null
          delivery_token: string | null
          delivery_email_sent_at: string | null
          employee_notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_type: 'translation' | 'interpretation' | 'equipment_rental' | 'notary'
          status?: string
          client_id: string
          source_lang?: string | null
          target_lang?: string | null
          specialty_id?: string | null
          word_count?: number | null
          document_path?: string | null
          ai_draft_path?: string | null
          translated_doc_path?: string | null
          document_name?: string | null
          ai_translation_started_at?: string | null
          ai_translation_completed_at?: string | null
          scheduled_at?: string | null
          duration_minutes?: number | null
          location_type?: 'in_person' | 'phone' | 'video' | null
          location_details?: string | null
          interpreter_notes?: string | null
          rental_start_date?: string | null
          rental_end_date?: string | null
          rental_items?: Json | null
          deposit_amount?: number | null
          deposit_refunded_at?: string | null
          dispatch_at?: string | null
          return_at?: string | null
          notary_service_type?: 'notary' | 'apostille' | 'both' | null
          delivery_method?: 'in_person' | 'mail' | null
          appointment_at?: string | null
          quote_per_word_rate?: number | null
          quote_multiplier?: number | null
          quote_amount?: number | null
          quote_adjusted_amount?: number | null
          quote_finalized_at?: string | null
          quote_token?: string | null
          quote_token_expires_at?: string | null
          quote_accepted_at?: string | null
          stripe_payment_intent_id?: string | null
          stripe_checkout_session_id?: string | null
          invoice_number?: string | null
          invoice_issued_at?: string | null
          payment_collected_at?: string | null
          assigned_translator_id?: string | null
          assigned_at?: string | null
          deadline_at?: string | null
          delivered_at?: string | null
          delivery_token?: string | null
          delivery_email_sent_at?: string | null
          employee_notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_type?: 'translation' | 'interpretation' | 'equipment_rental' | 'notary'
          status?: string
          client_id?: string
          source_lang?: string | null
          target_lang?: string | null
          specialty_id?: string | null
          word_count?: number | null
          document_path?: string | null
          ai_draft_path?: string | null
          translated_doc_path?: string | null
          document_name?: string | null
          ai_translation_started_at?: string | null
          ai_translation_completed_at?: string | null
          scheduled_at?: string | null
          duration_minutes?: number | null
          location_type?: 'in_person' | 'phone' | 'video' | null
          location_details?: string | null
          interpreter_notes?: string | null
          rental_start_date?: string | null
          rental_end_date?: string | null
          rental_items?: Json | null
          deposit_amount?: number | null
          deposit_refunded_at?: string | null
          dispatch_at?: string | null
          return_at?: string | null
          notary_service_type?: 'notary' | 'apostille' | 'both' | null
          delivery_method?: 'in_person' | 'mail' | null
          appointment_at?: string | null
          quote_per_word_rate?: number | null
          quote_multiplier?: number | null
          quote_amount?: number | null
          quote_adjusted_amount?: number | null
          quote_finalized_at?: string | null
          quote_token?: string | null
          quote_token_expires_at?: string | null
          quote_accepted_at?: string | null
          stripe_payment_intent_id?: string | null
          stripe_checkout_session_id?: string | null
          invoice_number?: string | null
          invoice_issued_at?: string | null
          payment_collected_at?: string | null
          assigned_translator_id?: string | null
          assigned_at?: string | null
          deadline_at?: string | null
          delivered_at?: string | null
          delivery_token?: string | null
          delivery_email_sent_at?: string | null
          employee_notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      job_status_history: {
        Row: {
          id: string
          job_id: string
          old_status: string | null
          new_status: string
          changed_by: string | null
          note: string | null
          created_at: string
        }
        Insert: {
          id?: string
          job_id: string
          old_status?: string | null
          new_status: string
          changed_by?: string | null
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          old_status?: string | null
          new_status?: string
          changed_by?: string | null
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      translator_invoices: {
        Row: {
          id: string
          job_id: string
          translator_id: string
          amount: number
          currency: string
          status: 'submitted' | 'approved' | 'queued' | 'paid' | 'failed'
          invoice_number: string | null
          submitted_at: string
          approved_at: string | null
          approved_by: string | null
          payout_due_at: string | null
          stripe_transfer_id: string | null
          paid_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          translator_id: string
          amount: number
          currency?: string
          status?: 'submitted' | 'approved' | 'queued' | 'paid' | 'failed'
          invoice_number?: string | null
          submitted_at?: string
          approved_at?: string | null
          approved_by?: string | null
          payout_due_at?: string | null
          stripe_transfer_id?: string | null
          paid_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          translator_id?: string
          amount?: number
          currency?: string
          status?: 'submitted' | 'approved' | 'queued' | 'paid' | 'failed'
          invoice_number?: string | null
          submitted_at?: string
          approved_at?: string | null
          approved_by?: string | null
          payout_due_at?: string | null
          stripe_transfer_id?: string | null
          paid_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      email_log: {
        Row: {
          id: string
          job_id: string | null
          email_type: string
          recipient: string
          subject: string
          sent_at: string
          resend_id: string | null
          status: 'sent' | 'failed'
          error_message: string | null
        }
        Insert: {
          id?: string
          job_id?: string | null
          email_type: string
          recipient: string
          subject: string
          sent_at?: string
          resend_id?: string | null
          status?: 'sent' | 'failed'
          error_message?: string | null
        }
        Update: {
          id?: string
          job_id?: string | null
          email_type?: string
          recipient?: string
          subject?: string
          sent_at?: string
          resend_id?: string | null
          status?: 'sent' | 'failed'
          error_message?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_invoice_number: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      is_employee: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
